Repository ssb-ngi-pointer/go-ssb-room, pull requests merged in 2021-03, with the labels that each got.

#77 Flesh out development instructions
  README.md
Labels: Documentation

#80 style the invite-list page
  web/i18n/defaults/active.en.toml
  web/templates/admin/invite-list.tmpl
Labels: Styling

#78 Aliases: database and web/muxrpc handlers
  aliases/confirm.go
  aliases/confirm_test.go
  aliases/names.go
  aliases/names_test.go
  cmd/server/main.go
  muxrpc/handlers/alias/handler.go
  muxrpc/handlers/tunnel/server/connect.go
  muxrpc/handlers/tunnel/server/plugin.go
  muxrpc/handlers/tunnel/server/state.go
  muxrpc/handlers/whoami/whoami.go
  muxrpc/test/go/alias_test.go
  muxrpc/test/go/utils_test.go
  muxrpc/test/nodejs/announce_test.go
  muxrpc/test/nodejs/setup_test.go
  roomdb/interface.go
  roomdb/mockdb/alias.go
  roomdb/sqlite/aliases.go
  roomdb/sqlite/aliases_test.go
  roomdb/sqlite/migrations/5-aliases.sql
  roomdb/sqlite/models/aliases.go
  roomdb/sqlite/models/allow_list.go
  roomdb/sqlite/models/auth_fallback.go
  roomdb/sqlite/models/boil_table_names.go
  roomdb/sqlite/new.go
  roomdb/sqlite/roomcfg.go
  roomdb/types.go
  roomsrv/init_handlers.go
  roomsrv/init_network.go
  roomsrv/init_unixsock.go
  roomsrv/manifest.go
  roomsrv/server.go
  web/handlers/admin/aliases.go
  web/handlers/admin/aliases_test.go
  web/handlers/admin/allow_list.go
  web/handlers/admin/app_test.go
  web/handlers/admin/handler.go
  web/handlers/aliases.go
  web/handlers/aliases_test.go
  web/handlers/basic_test.go
  web/handlers/http.go
  web/handlers/invites.go
  web/handlers/invites_test.go
  web/handlers/setup_test.go
  web/i18n/defaults/active.en.toml
  web/router/admin.go
  web/router/complete.go
  web/templates/admin/aliases-revoke-confirm.tmpl
  web/templates/admin/aliases.tmpl
  web/templates/aliases-resolved.html
  web/templates/menu.tmpl
Labels: Go

#64 Add tests for notices view
  .gitignore
  roomdb/interface.go
  roomdb/sqlite/auth_fallback.go
  roomdb/sqlite/notices_test.go
  web/handlers/admin/aliases_test.go
  web/handlers/admin/allow_list_test.go
  web/handlers/admin/app_test.go
  web/handlers/admin/invites_test.go
  web/handlers/admin/notices.go
  web/handlers/admin/notices_test.go
  web/handlers/invites_test.go
  web/handlers/notices_test.go
  web/templates/notice/show.tmpl
  web/utils.go
  web/webassert/asserts.go
Labels: Go

#85 Use new ssb-room client module
  go.mod
  go.sum
  muxrpc/test/nodejs/announce_test.go
  muxrpc/test/nodejs/package-lock.json
  muxrpc/test/nodejs/package.json
  muxrpc/test/nodejs/sbot_client.js
  muxrpc/test/nodejs/sbot_serv.js
  muxrpc/test/nodejs/setup_test.go
  muxrpc/test/nodejs/testscripts/client-opening-tunnel.js
  muxrpc/test/nodejs/testscripts/client.js
  muxrpc/test/nodejs/testscripts/legacy_client.js
  muxrpc/test/nodejs/testscripts/legacy_client_opening_tunnel.js
  muxrpc/test/nodejs/testscripts/legacy_server.js
  muxrpc/test/nodejs/testscripts/minimal-before-setup.js
  muxrpc/test/nodejs/testscripts/modern_client.js
  muxrpc/test/nodejs/testscripts/modern_client_opening_tunnel.js
  muxrpc/test/nodejs/testscripts/secretstack-legacy.js
  muxrpc/test/nodejs/testscripts/secretstack-modern.js
  muxrpc/test/nodejs/testscripts/secretstack_testplugin.js
  muxrpc/test/nodejs/testscripts/server.js
  muxrpc/test/nodejs/testscripts/simple_client.js
  muxrpc/test/nodejs/testscripts/simple_client_opening_tunnel.js
  muxrpc/test/nodejs/testscripts/template.js
  muxrpc/test/nodejs/tunnel_connect_test.go
Labels: JavaScript, Testing

#95 add JS test for alias register and revoke
  cmd/server/main.go
  internal/aliases/confirm.go
  internal/aliases/confirm_test.go
  internal/aliases/names.go
  internal/aliases/names_test.go
  muxrpc/handlers/alias/handler.go
  muxrpc/test/go/alias_test.go
  muxrpc/test/go/utils_test.go
  muxrpc/test/nodejs/aliases_test.go
  muxrpc/test/nodejs/package-lock.json
  muxrpc/test/nodejs/package.json
  muxrpc/test/nodejs/setup_test.go
  muxrpc/test/nodejs/testscripts/modern_aliases.js
  roomsrv/init_handlers.go
  roomsrv/server.go
  web/handlers/aliases.go
Labels: JavaScript, Testing

#90 go side of sign-in with ssb
  cmd/server/main.go
  go.mod
  go.sum
  internal/network/interface.go
  internal/network/mocked/endpoints.go
  internal/randutil/string.go
  internal/signinwithssb/bridge.go
  internal/signinwithssb/bridge_test.go
  internal/signinwithssb/challenges.go
  internal/signinwithssb/simple_test.go
  muxrpc/handlers/gossip/ping.go
  muxrpc/handlers/signinwithssb/withssb.go
  muxrpc/test/go/alias_test.go
  muxrpc/test/go/utils_test.go
  muxrpc/test/nodejs/setup_test.go
  roomdb/interface.go
  roomdb/mockdb/auth.go
  roomdb/mockdb/members.go
  roomdb/sqlite/auth_withssb.go
  roomdb/sqlite/invites.go
  roomdb/sqlite/migrations/01-consolidated.sql
  roomdb/sqlite/migrations/03-siwssb-tokens.sql
  roomdb/sqlite/models/SIWSSB_sessions.go
  roomdb/sqlite/models/aliases.go
  roomdb/sqlite/models/boil_table_names.go
  roomdb/sqlite/models/denied_keys.go
  roomdb/sqlite/models/members.go
  roomdb/sqlite/new.go
  roomdb/sqlite/new_test.go
  roomsrv/init_handlers.go
  roomsrv/server.go
  web/assets/login-events.js
  web/errors/badrequest.go
  web/handlers/admin/setup_test.go
  web/handlers/aliases.go
  web/handlers/auth/handler.go
  web/handlers/auth/withssb.go
  web/handlers/auth_test.go
  web/handlers/http.go
  web/handlers/invites.go
  web/handlers/notices_test.go
  web/handlers/setup_test.go
  web/i18n/defaults/active.en.toml
  web/members/helper.go
  web/members/testing.go
  web/router/auth.go
  web/router/complete.go
  web/templates/admin/members-remove-confirm.tmpl
  web/templates/aliases-resolved.html
  web/templates/auth/decide_method.tmpl
  web/templates/auth/fallback_sign_in.tmpl
  web/templates/auth/withssb_server_start.tmpl
  web/templates/base.tmpl
  web/webassert/asserts.go
Labels: Go

#105 Add support for invite consumption via JSON
  cmd/insert-user/main.go
  cmd/server/main.go
  internal/network/interface.go
  muxrpc/test/go/alias_test.go
  muxrpc/test/go/simple_test.go
  muxrpc/test/nodejs/aliases_test.go
  muxrpc/test/nodejs/tunnel_connect_test.go
  roomdb/interface.go
  roomdb/mockdb/invites.go
  roomdb/mockdb/members.go
  roomdb/sqlite/aliases_test.go
  roomdb/sqlite/invites.go
  roomdb/sqlite/invites_test.go
  roomdb/sqlite/members.go
  roomdb/sqlite/members_test.go
  roomdb/sqlite/migrations/01-consolidated.sql
  roomdb/sqlite/models/invites.go
  roomdb/sqlite/models/members.go
  roomdb/sqlite/new_test.go
  roomdb/types.go
  web/handlers/admin/invites.go
  web/handlers/admin/invites_test.go
  web/handlers/admin/members.go
  web/handlers/admin/members_test.go
  web/handlers/admin/setup_test.go
  web/handlers/auth/withssb.go
  web/handlers/auth_test.go
  web/handlers/http.go
  web/handlers/invites.go
  web/handlers/invites_test.go
  web/handlers/notices_test.go
  web/i18n/defaults/active.en.toml
  web/router/complete.go
  web/templates/admin/invite-created.tmpl
  web/templates/admin/invite-list.tmpl
  web/templates/admin/invite-revoke-confirm.tmpl
  web/templates/admin/members.tmpl
  web/templates/base.tmpl
  web/templates/invite/accept.tmpl
  web/templates/invite/consumed.tmpl
  web/templates/invite/facade.tmpl
Labels: Go
