Repository ssb-ngi-pointer/go-ssb-room, pull requests merged in 2021-05, with the labels that each got.

#209 have a clear error on taken aliases
  muxrpc/handlers/alias/handler.go
  muxrpc/test/go/alias_test.go
  roomdb/sqlite/aliases.go
  roomdb/sqlite/aliases_test.go
  roomdb/types.go
Labels: Go

#207 Bugfixing
  go.mod
  go.sum
  muxrpc/handlers/tunnel/server/connect.go
  muxrpc/handlers/tunnel/server/state.go
  web/handlers/admin/aliases.go
  web/handlers/admin/handler.go
  web/handlers/notices_test.go
  web/handlers/setup_test.go
  web/utils.go
Labels: Go

#65 add wip personal notes on testing
  docs/testing.md
Labels: Testing

#52 Track style css
  .github/workflows/go.yml
  .gitignore
  README.md
  web/assets/style.css
Labels: Go, Styling
